Added tutorial page
CapituloJaverianoACM/community-service pull request #16
Opened 2021-05-03 03:46 UTC by camiloserr

-Added routing
-Added tutorial component
-Tutorial tabs are hiding until the button is clicked
-Added links to footer icons
Closes #14

2021-05-08 17:08 UTC, mateoflorido requested changes
No olviden eliminar el package-lock.json del repo local de cada uno. Además de instalar yarn como instalador de paquetes.

El botón de "Comenzar" debería de estar centrado en el componente. Se ve un poco fuera de lugar en general. Otra opción podría ser extraerlo del componente y solo mostrarlo cuando se muestre la última página del tutorial. O en su defecto, dejarlo siempre por si alguien no quiere ver el tutorial y quiere usar Community de una.

2021-05-08 17:10 UTC, ayurojasn commented
Listo!

Lo del botón de comenzar y esas mismas sugerencias creo que Camilo lo estaba cambiando.

2021-05-08 22:47 UTC, ayurojasn approved these changes

2021-05-09 00:11 UTC, mateoflorido approved these changes

2021-05-09 00:36 UTC, mateoflorido commented
Perfecto. Podríamos realizar el merge ahora.

2021-05-09 00:37 UTC, mateoflorido approved these changes
OK!

2021-05-09 00:42 UTC, merged